
INSERT INTO ACCOUNT (ID, FIRSTNAME, LASTNAME, ACCOUNTNUMBER) VALUES(1, 'John', 'Doe', '1234') 

INSERT INTO ACCOUNT (ID, FIRSTNAME, LASTNAME, ACCOUNTNUMBER) VALUES(2, 'Jane', 'Doe', '1235') 

INSERT INTO ACCOUNT (ID, FIRSTNAME, LASTNAME, ACCOUNTNUMBER) VALUES(3, 'Jim', 'Taylor', '1236') 

INSERT INTO TRANSACTION(TRANSACTION_ID,NAME,ACCOUNT_ID) VALUES(1, 'John',1) 

INSERT INTO TRANSACTION(TRANSACTION_ID,NAME,ACCOUNT_ID) VALUES(2, 'Jane',2) 

INSERT INTO TRANSACTION(TRANSACTION_ID,NAME,ACCOUNT_ID) VALUES(3, 'Jim',3) 